# 仅需要添加与default不相同的配置
# 本地开发环境

# redis 配置
redis:
  uri: redis://127.0.0.1:6379/?slow=200ms&maxProcessing=1000

# database配置
database:
  uri: postgres://vicanso:A123456@127.0.0.1:5432/tiny?maxIdleConns=5&maxIdleTime=30m&maxOpenConns=10