# production 生产环境中使用的相关配置

# redis 配置
redis: redis://:PASS@172.18.109.188:6379

# tiny 配置tiny服务的IP
tiny:
  host: 172.18.109.188
  port: 7002

# postgres 配置
postgres:
  host: 172.18.109.188
  password: PASS

# 预览地址
imagePreview:
  url: "https://tiny.npmtrend.com/images/v1/preview/:zone/:file"